url: http://uncommonplaces.com
name: Ida C. Benedetto
description: >
  Media Strategy, Event Production, Game
  Design, Website Development

permalink:    /:year/:month/:title/

collections:
  projects:
    output: true
    permalink: /projects/:path/


paginate: 15
paginate_path: "posts/page:num/"